'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Build job 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install node 16
      uses: actions/setup-node@v1
      with: 
       node-version: 16.x

    - name: install NPM Dependencies
      run: npm i

    - name: Build Project
      run: npm run build

    - name: Upload artifact in order to deploy 
      uses: actions/upload-artifact@v2

      with:
        name:  production-files
        path: ./dist


#deploy job
  deploy:
   name: Deploy 
   runs-on: ubuntu-latest
   needs: build

   steps:
     - name: Download artifact
       uses: actions/download-artifact@v2
       with: 
         name: production-files
         path: ./dist

     - name: Deploy to gh pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GH_PAGES }}
         publish_dir: ./dist
      

       
